### PR TITLE
Use `DefaultApplication`

### LINKED ISSUE #22: Try DefaultApplication.jl for opening the generated .pptx
Proposed in a PR, we can look into [DefaultApplication.jl](https://github.com/tpapp/DefaultApplication.jl) to open the generated .pptx file after `write("file.ppt", presentation; open_ppt=true)`.

Currently we use this custom code: 
```julia
    if open_ppt
        try
            if Sys.iswindows()
                run(`cmd /C start powerpnt.exe /C $filepath`)
            elseif Sys.isapple()
                run(`open $filepath`)
            else
                run(`xdg-open $filepath`)
            end
        catch err
            @warn "Could not open file $filepath"
            bt = backtrace()
            print(sprint(showerror, err, bt))
        end
    end
```

### PR DESCRIPTION
**Pull request by this-josh**
A small PR which I believe closes #22 ,I've changed `open_ppt` to use `DefaultApplication`.

### CODE REVIEW

**Comment by matthijscox-asml** [comment]
Since this line of code is untested automatically... on which operating system did you test this manually?

**Comment by this-josh** [comment]
I tested it on MacOS 13.1, testing it in CI is rather tricky. https://github.com/tpapp/DefaultApplication.jl#testing

**Comment by matthijscox-asml** [comment]
Yes, let's assume the package just works and keep the CI simple here. 

I'm wondering whether to add back the try/catch and throw a warning instead of an error when the file cannot open, one user already got confused since it seemed that the writing failed. On the other hand, that's more code to (not) test. So I'm okay to trust DefaultApplication.jl for now.

Feel free to version bump to v0.5.3, then I'll register right after merging this PR.

**Comment by this-josh** [comment]
Sure.

It could be best to change the if statement to 
```julia
    if open_ppt && isfile(filepath)
            DefaultApplication.open(filepath)
    end
```
and then let the error be handled by `DefaultApplication.jl`.

**Comment by matthijscox-asml** [comment]
I'm assuming that if the file writing fails, it errors and never reaches the open_ppt if-statement. 
Do you foresee a possibility where the file is not written, but we still reach the open_ppt statement?

**Comment by this-josh** [comment]
I cannot envisage this scenario, but I presumed from
> one user already got confused since it seemed that the writing failed

that it has occurred in some edge case, unless the file was written but failed to open because it was corrupted? 

It's worth noting that `DefaultApplication` doesn't raise an error if the file doesn't exist.

**Comment by matthijscox-asml** [comment]
> that it has occurred in some edge case, unless the file was written but failed to open because it was corrupted?

No, what happened was that the file was successfully written, but an opening error was thrown and the user thought the file was not written.

I'll merge and register. Let's assume DefaultApplication works decently enough.

**Comment by this-josh** [comment]
I see. 

I think that is a good plan.

**Pull request merged**
