### PR TITLE
Add content types for picture formats

### LINKED ISSUE #28: add picture with .wmf , .emf format will result corrupted pptx file while opening with M$office
Picture("xxx.wmf") can be added to Presentation . But when opend the output file , it showed corrupted file message

### PR DESCRIPTION
**Pull request by jaakkor2**
Fix #28 and #32.

### CODE REVIEW

**Comment by matthijscox-asml** [comment]
Excellent! Feel free to immediately version bump the Project.toml so we can release this fix. Else I'll just do it in a separate PR.

**Comment by jaakkor2** [comment]
Done @matthijscox-asml .

**Comment by hellemo** [comment]
With v0.6.4 I get an error: ```ERROR: SystemError: opening file "../[Content_Types].xml": Permission denied```

**Comment by jaakkor2** [comment]
> With v0.6.4 I get an error: `ERROR: SystemError: opening file "../[Content_Types].xml": Permission denied`

Which template are you using? Which OS?

Code creates a tmp directory and changes into `ppt` folder there.  `[Content_Types].xml` should be at one directory level higher.
https://github.com/ASML-Labs/PPTX.jl/blob/v0.6.3/src/write.jl#L153-L154

**Comment by jaakkor2** [comment]
Weird, I do get the same error with `]add PPTX@0.6.4`, but not if I `]dev PPTX`.  I am on Julia 1.10.0-beta1 on Windows.

**Comment by matthijscox-asml** [comment]
Wait, are you editing the template file directly (which is stored in .julia/packages, which is probably read-only)?
Or maybe the path got pre-compiled into the code?

I propose to make the input ppt path a variable again (and to use `abspath` so we can see where it's located). Let me do try to do that right now

**Comment by jaakkor2** [comment]
Putting `@show pwd()` into `add_contenttypes!` shows the temp directory
`pwd() = "C:\\Users\\jaakkor2\\AppData\\Local\\Temp\\jl_3DqpiT\\no-slides\\ppt"`

Why would CI pass?

**Comment by matthijscox-asml** [comment]
Hmm, if the path got compiled into the function upon the first run, then we should have still found out when the unit tests call `PPTX.write` the second time...

**Pull request merged**
