### PR TITLE
Remove `unzip` and `zip` and use ZipArchives.jl instead

### LINKED ISSUE #14: Switch to using ZipFile.jl
We encountered some issues with the p7zip_jll binary library we currently use. The [issue](https://github.com/ASML-Labs/PPTX.jl/issues/2) was that resolved with a workaround, but perhaps ZipFile.jl (also used by XLSX.jl) is a better approach.

We have the start of a [ZipFile PR](https://github.com/ASML-Labs/PPTX.jl/pull/13), but it's incomplete.

### PR DESCRIPTION
**Pull request by nhz2**
Fixes #14 by using [ZipArchives.jl](https://github.com/medyan-dev/ZipArchives.jl)

ZipArchives.jl is a new package I made to read Zarr data, and it works for PPTX as well.

Lastly, in this PR I removed the ability to use template directories, only files are allowed.

### CODE REVIEW

**Comment by matthijscox-asml** [comment]
You put some serious effort into this!

I don't know if @jvieyras and/or @xvries have some time to review as well?

**Comment by nhz2** [comment]
I updated this PR to the latest version of main.

@matthijscox-asml @jaakkor2 This PR also resolves the problems in #47. With this PR there is no need to mess with file permissions or directories because everything stays as zip files.

**Comment by matthijscox-asml** [comment]
> @matthijscox-asml @jaakkor2 This PR also resolves the problems in https://github.com/ASML-Labs/PPTX.jl/pull/47. With this PR there is no need to mess with file permissions or directories because everything stays as zip files.

That would be another good reason to go with your changes :)

But you do not expect issues with editing the zip files, if the zip file is read-only from the Pkg.add ?

**Comment by nhz2** [comment]
In this PR the only thing I do with the template file is `read`, I never use the `cp` function.

To avoid changing an existing zip file, I keep track of two separate zip file objects when writing the presentation.

One is `template_reader = ZipBufferReader(read(template_path))`
This is a read-only ZipReader of the template.

The other is `ZipWriter(temp_out; own_io=true) do w`
This is an append-only ZipWriter for the new file.

`w` starts out completely empty, and files that need to be different from the template are added to it in:

```julia
update_presentation_state!(p, template_reader)
write_relationships!(w, p)
write_presentation!(w, p)
write_slides!(w, p, template_reader)
write_shapes!(w, p)
update_table_style!(w, template_reader)
add_contenttypes!(w, template_reader)
```
Then only after all of the files that needed to be edited were written, do I copy over all other files from the template that are not yet in `w`.

```julia
# copy over any files from the template
# but don't overwrite any files in w
for i in zip_nentries(template_reader):-1:1
    local name = zip_name(template_reader, i)
    if !endswith(name,"/")
        if !zip_name_collision(w, name)
            local compress = zip_iscompressed(template_reader, i)
            zip_data = zip_readentry(template_reader, i)
            zip_newfile(w, name; compress)
            write(w, zip_data)
            zip_commitfile(w)
        end
    end
end
```

In this way no zip file entry needs to be edited or deleted, only read and append operations are needed.

**Comment by matthijscox-asml** [comment]
okay, i agree this looks good! hmm, I've decided to go with it.

do you want to do a release 1.0 of ZipArchives.jl first before merging this?

**Comment by nhz2** [comment]
Sure, I'll make sure to do that. Thanks for reviewing this.

**Comment by matthijscox-asml** [comment]
I was ill for a while so this took a bit longer than expected.

I see that there's a silly error in the docs test that needs a fix (although I don't know why it suddenly needs `DataFrames.DataFrame` instead of `DataFrame`, but it's easy enough to change that)

If you want you can also update the Project.toml and bump it to v0.7.0, then I'll register a new version after merging this PR.

**Pull request merged**
